name: Actions Workflow

on: [push]

# on:
#   push:
#     branches:
#       - master
#       - 'feature/*' #matches feature/anything but not feature/a/b
#       - 'feature/**' #will match feature/feature/feature
#       - '!feature/**' #will be ignore when use !
#      branches-ignore:
#       - 'feature/' will run all branches except feature/*, can't use with brnches
#       tags:
#         -va.*
#       paths:
#         -'**.js' # will match any file that match
#   repositary_dispatch:
#     types: [build]
#   schedule:
#     -cron: "0/5 * * * *"
#   pull_request: 
#     types: [closed,assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: payload
        run: echo${{github.event.client_payload.env}}

      - name: List Files
        run: |
          pwd
          ls -a
          
      - name: Checkout
        uses: actions/checkout@v1
      - name: List File after Checkout
        run: |
          pwd 
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Low
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
