name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files
        run: |
          pwd 
          ls
      - name: List File after Checkout
        uses: action/checkout@v1
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Low
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
